### PR TITLE
implement integration tests

### PR DESCRIPTION
**Pull request by C0rby**
Implemented tests for the thumbnails grpc api

Changed the method `NewService` to be able to configure different image sources and thumbnail storages during initialization. This also improves testability.
Source and Storage are now provided through the options.
 https://github.com/owncloud/ocis-thumbnails/blob/edaac10872733eea4172ca0d11187fd4994d5155/pkg/service/v0/service.go#L15-L33

### CODE REVIEW

**Comment by refs** [comment]
This PR goes beyond simple tests; the behavior of the extension changed, and such changes should be reflected on the PR description or a changelog file to capture the intent of the changes.

Are the changes forced so tests can be written around it or were they actually a design choice?

I believe integration tests need some discussion, which is the kind of tests I'm reading here, as the service is being tested from the outside 🤔 if these were unit tests it would be perfectly fine, but I think we need to involve the testing team for this. There is also something profound that bother me, I wouldn't write tests for files generated by `protobuf`, as they are subject to changes.

**Comment by refs** [comment]
Piggybacking on my previous comment, I'm use to do integration tests (personally) in JS paired with snapshot testing tool like [Jest](https://jestjs.io/), hence I tag @micbar

**Comment by micbar** [comment]
@refs We did a concept with Thomas and @individual-it where we do integration tests in go.

In the past, we did Integration tests in Gherkin with a testing framework, which produced a lot of overhead.

Thomas introduced a concept, where we are testing the handlers directly without running the whole service

**Comment by individual-it** [comment]
here is what we have done in the ocis-hello repo @refs has been part of the implementation
https://github.com/owncloud/ocis-hello/pull/55

Please have a look at the discussion that lead to this approach: 
https://github.com/owncloud/ocis-hello/pull/32
https://github.com/owncloud/ocis-hello/pull/37

**Comment by refs** [comment]
> here is what we have done in the ocis-hello repo @refs has been part of the implementation
> [owncloud/ocis-hello#55](https://github.com/owncloud/ocis-hello/pull/55)
> 
> Please have a look at the discussion that lead to this approach:
> [owncloud/ocis-hello#32](https://github.com/owncloud/ocis-hello/pull/32)
> [owncloud/ocis-hello#37](https://github.com/owncloud/ocis-hello/pull/37)

Nice discussion! sorry I bring this up again, was not aware of the entire arguments. I'm okay with this approach now that I have more context. Thanks!

**Comment by C0rby** [comment]
> This PR goes beyond simple tests; the behavior of the extension changed, and such changes should be reflected on the PR description or a changelog file to capture the intent of the changes.
> 
> Are the changes forced so tests can be written around it or were they actually a design choice?
> 
Yeah, the changes were made to allow changing the image source and thumbnail storage for testing.
Should I write a changelog for that?

**Comment by refs** [comment]
> > This PR goes beyond simple tests; the behavior of the extension changed, and such changes should be reflected on the PR description or a changelog file to capture the intent of the changes.
> > Are the changes forced so tests can be written around it or were they actually a design choice?
> 
> Yeah, the changes were made to allow changing the image source and thumbnail storage for testing.
> Should I write a changelog for that?

A tiny Changelog would be pretty appreciated ^^

**Comment by refs** [comment]
> > This PR goes beyond simple tests; the behavior of the extension changed, and such changes should be reflected on the PR description or a changelog file to capture the intent of the changes.
> > Are the changes forced so tests can be written around it or were they actually a design choice?
> 
> Yeah, the changes were made to allow changing the image source and thumbnail storage for testing.
> Should I write a changelog for that?

I think updating the PR description should be enough ^^

**Comment by micbar** [comment]
@C0rby Coulds you do a rebase instead of merging master branch in the PR?

**Comment by C0rby** [comment]
Sure

**Pull request merged**
