### PR TITLE
fix program flags

### LINKED ISSUE #15: Thumbnail service not supporting log level
All services can be started with `./ocis --log-level debug service_name` except the thumbnails one.

Thumbnails gives this:
```
% bin/ocis --log-level debug thumbnails
2020-04-16T15:47:03+02:00 DBG Tracing is not enabled service=thumbnails
2020-04-16T15:47:03+02:00 INF Starting server addr=0.0.0.0:9185 service=thumbnails transport=grpc
Incorrect Usage. flag provided but not defined: -log-level

NAME:
   com.owncloud.api.thumbnails - a go-micro service

USAGE:
   ocis [global options] command [command options] [arguments...]

COMMANDS:
   help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --client value                  Client for go-micro; rpc [$MICRO_CLIENT]
   --client_request_timeout value  Sets the client request timeout. e.g 500ms, 5s, 1m. Default: 5s [$MICRO_CLIENT_REQUEST_TIMEOUT]
   --client_retries value          Sets the client retries. Default: 1 (default: 1) [$MICRO_CLIENT_RETRIES]
   --client_pool_size value        Sets the client connection pool size. Default: 1 (default: 0) [$MICRO_CLIENT_POOL_SIZE]
   --client_pool_ttl value         Sets the client connection pool ttl. e.g 500ms, 5s, 1m. Default: 1m [$MICRO_CLIENT_POOL_TTL]
   --register_ttl value            Register TTL in seconds (default: 60) [$MICRO_REGISTER_TTL]
   --register_interval value       Register interval in seconds (default: 30) [$MICRO_REGISTER_INTERVAL]
   --server value                  Server for go-micro; rpc [$MICRO_SERVER]
   --server_name value             Name of the server. go.micro.srv.example [$MICRO_SERVER_NAME]
   --server_version value          Version of the server. 1.1.0 [$MICRO_SERVER_VERSION]
   --server_id value               Id of the server. Auto-generated if not specified [$MICRO_SERVER_ID]
   --server_address value          Bind address for the server. 127.0.0.1:8080 [$MICRO_SERVER_ADDRESS]
   --server_advertise value        Used instead of the server_address when registering with discovery. 127.0.0.1:8080 [$MICRO_SERVER_ADVERTISE]
   --server_metadata value         A list of key-value pairs defining metadata. version=1.0.0 [$MICRO_SERVER_METADATA]
   --broker value                  Broker for pub/sub. http, nats, rabbitmq [$MICRO_BROKER]
   --broker_address value          Comma-separated list of broker addresses [$MICRO_BROKER_ADDRESS]
   --profile value                 Debug profiler for cpu and memory stats [$MICRO_DEBUG_PROFILE]
   --registry value                Registry for discovery. etcd, mdns [$MICRO_REGISTRY]
   --registry_address value        Comma-separated list of registry addresses [$MICRO_REGISTRY_ADDRESS]
   --runtime value                 Runtime for building and running services e.g local, kubernetes (default: "local") [$MICRO_RUNTIME]
   --runtime_source value          Runtime source for building and running services e.g github.com/micro/service (default: "github.com/micro/services") [$MICRO_RUNTIME_SOURCE]
   --selector value                Selector used to pick nodes for querying [$MICRO_SELECTOR]
   --store value                   Store used for key-value storage [$MICRO_STORE]
   --store_address value           Comma-separated list of store addresses [$MICRO_STORE_ADDRESS]
   --store_namespace value         Namespace for store data [$MICRO_STORE_NAMESPACE]
   --transport value               Transport mechanism used; http [$MICRO_TRANSPORT]
   --transport_address value       Comma-separated list of transport addresses [$MICRO_TRANSPORT_ADDRESS]
   --tracer value                  Tracer for distributed tracing, e.g. memory, jaeger [$MICRO_TRACER]
   --tracer_address value          Comma-separated list of tracer addresses [$MICRO_TRACER_ADDRESS]
   --auth value                    Auth for role based access control, e.g. service [$MICRO_AUTH]
   --auth_public_key value         Public key for JWT auth (base64 encoded PEM) [$MICRO_AUTH_PUBLIC_KEY]
   --auth_private_key value        Private key for JWT auth (base64 encoded PEM) [$MICRO_AUTH_PRIVATE_KEY]
   --auth_exclude value            Comma-separated list of endpoints excluded from authentication [$MICRO_AUTH_EXCLUDE]
   --help                          Show the help (default: false)
flag provided but not defined: -log-level
```

Other services like phoenix gives no such output.

Happening on master (b16636c69dcbfe56bbee51137c5eebb70445b257) today.

### PR DESCRIPTION
**Pull request by C0rby**
Fixes #15

### CODE REVIEW

**Comment by micbar** [comment]
Did you test setting options on the root command and in standalone mode?

**Comment by C0rby** [comment]
> Did you test setting options on the root command and in standalone mode?

What do you mean by root command?

**Comment by micbar** [comment]
Test setting options using the single binary, and then test it directly on the thumbnails binary

**Comment by C0rby** [comment]
Ah yes. Both worked for me.

**Pull request merged**
